Repository AICoE/aicoe-sre, pull requests merged in 2020-06, with the labels that each got.

#1 Add Basic Monitoring Setup
  README.md
  monitoring/prometheus/README.md
  monitoring/prometheus/psi-ocp.yaml
  monitoring/servicemonitors/aicoe-argocd.yaml
Labels: approved, size/L

#2 Add jupyterhub
  applications/jupyterhub/README.md
  applications/jupyterhub/bases/custom-images/jupyterhub-custom-images.yaml
  applications/jupyterhub/bases/custom-images/kustomization.yaml
  applications/jupyterhub/bases/custom-profiles/jupyterhub-singleuser-profiles.yaml
  applications/jupyterhub/bases/custom-profiles/kustomization.yaml
  applications/jupyterhub/bases/jupyterhub/configs/jupyterhub_config.py
  applications/jupyterhub/bases/jupyterhub/jupyterhub.yaml
  applications/jupyterhub/bases/jupyterhub/kustomization.yaml
  applications/jupyterhub/overlays/dev/jupyterhub.yaml
  applications/jupyterhub/overlays/dev/kustomization.yaml
  applications/jupyterhub/overlays/prod/kustomization.yaml
  applications/jupyterhub/overlays/prod/membership.yaml
  applications/jupyterhub/overlays/stage/jupyterhub.yaml
  applications/jupyterhub/overlays/stage/kustomization.yaml
  applications/jupyterhub/overlays/stage/membership.yaml
  monitoring/prometheus/README.md
  runbooks/jupyterhub.md
Labels: size/XXL

#5 Remove images that are handled by odh
  applications/jupyterhub/bases/custom-images/jupyterhub-custom-images.yaml
Labels: approved, size/L

#7 Update JupyterHub ODH CR for spark variable changes
  applications/jupyterhub/bases/jupyterhub/jupyterhub.yaml
Labels: approved, size/M

#8 Add resources definition for spark custom profiles
  applications/jupyterhub/bases/custom-profiles/jupyterhub-singleuser-profiles.yaml
Labels: approved, size/XS

#9 Update Singleuser Profiles to new Spark config
  applications/jupyterhub/bases/custom-profiles/jupyterhub-singleuser-profiles.yaml
Labels: size/S

#11 Add ArgoCD Deployment for Prometheus
  monitoring/psi-prod-cluster/README.md
  monitoring/psi-prod-cluster/bases/prometheus/kustomization.yaml
  monitoring/psi-prod-cluster/bases/prometheus/psi-ocp.yaml
  monitoring/psi-prod-cluster/bases/servicemonitors/aicoe-argocd.yaml
  monitoring/psi-prod-cluster/bases/servicemonitors/kustomization.yaml
  monitoring/psi-prod-cluster/overlays/prod/kustomization.yaml
Labels: approved, size/S

#13 Move Argocd Monitor to aicoe-argocd application
  applications/aicoe-argocd/bases/servicemonitor/aicoe-argocd-monitor.yaml
  applications/aicoe-argocd/bases/servicemonitor/kustomization.yaml
  applications/aicoe-argocd/overlays/kustomization.yaml
Labels: size/XS

#14 Remove deleted file from prometheus kustomization
  monitoring/psi-prod-cluster/overlays/prod/kustomization.yaml
Labels: size/XS

#4 Add Jupyterhub SLIs to runbook
  runbooks/jupyterhub.md
Labels: approved, size/M

#15 Fix file path for argocd service monitor
  applications/aicoe-argocd/overlays/kustomization.yaml
Labels: size/XS

#18 Update Jupyterhub image to tag that supports tolerations
  applications/jupyterhub/bases/jupyterhub/jupyterhub.yaml
Labels: size/XS

#3 Update s2i-categorical-encoding image name
  applications/jupyterhub/bases/custom-images/jupyterhub-custom-images.yaml
Labels: size/XS

#19 Add rtripath to the AI Ops users customized list
  applications/jupyterhub/bases/custom-profiles/jupyterhub-singleuser-profiles.yaml
Labels: approved, size/XS

#22 Add Alertmanager Deployment
  monitoring/psi-prod-cluster/README.md
  monitoring/psi-prod-cluster/bases/alertmanager/alertmanager-route.yaml
  monitoring/psi-prod-cluster/bases/alertmanager/alertmanager.yaml
  monitoring/psi-prod-cluster/bases/alertmanager/kustomization.yaml
  monitoring/psi-prod-cluster/overlays/prod/kustomization.yaml
Labels: size/M

#17 Include thoth demo notebook in jupyterhub
  applications/jupyterhub/bases/custom-images/jupyterhub-custom-images.yaml
Labels: approved, size/S

#23 Add shanand
  applications/jupyterhub/overlays/prod/membership.yaml
Labels: size/XS

#21 Add a custom JupyterHub profile for users with 16 GB RAM
  applications/jupyterhub/bases/custom-profiles/jupyterhub-singleuser-profiles.yaml
Labels: approved, size/XS

#6 Add Argo and Argo Events applications
  applications/argo-events/README.md
  applications/argo-events/base/argo-events-user-role.yaml
  applications/argo-events/base/kustomization.yaml
  applications/argo-events/overlays/dh-dev-argo/kustomization.yaml
  applications/argo-events/overlays/dh-prod-argo/kustomization.yaml
  applications/argo-events/overlays/dh-prod-argo/membership.yaml
  applications/argo-events/overlays/dh-stage-argo/kustomization.yaml
  applications/argo-events/overlays/dh-stage-argo/membership.yaml
  applications/argo/README.md
  applications/argo/base/argo-server-route.yaml
  applications/argo/base/argo-user-role.yaml
  applications/argo/base/default-sa-role.yaml
  applications/argo/base/default-sa-rolebinding.yaml
  applications/argo/base/kustomization.yaml
  applications/argo/base/workflow-controller-configmap.yaml
  applications/argo/base/workflow-controller-metrics-route.yaml
  applications/argo/overlays/dh-dev-argo/kustomization.yaml
  applications/argo/overlays/dh-prod-argo/kustomization.yaml
  applications/argo/overlays/dh-prod-argo/membership.yaml
  applications/argo/overlays/dh-stage-argo/kustomization.yaml
  applications/argo/overlays/dh-stage-argo/membership.yaml
Labels: approved, size/L

#25 adding ImageStream for openshift sme mailing list analysis work
  applications/jupyterhub/bases/custom-images/jupyterhub-custom-images.yaml
Labels: approved
